name: Code Quality Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install ESLint
        run: npm install -g eslint htmlhint
      
      - name: Run ESLint
        run: eslint . --ext .js,.html || true
      
      - name: Run HTMLHint
        run: htmlhint "**/*.html" || true
