name: Code Quality Check & Auto-Fix

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install ESLint & HTMLHint
        run: npm install -g eslint htmlhint eslint-plugin-html
      
      - name: Create ESLint config
        run: |
          echo '{
            "env": {
              "browser": true,
              "es2021": true
            },
            "extends": "eslint:recommended",
            "parserOptions": {
              "ecmaVersion": "latest",
              "sourceType": "module"
            },
            "plugins": ["html"],
            "rules": {
              "no-unused-vars": "warn",
              "no-undef": "warn"
            }
          }' > .eslintrc.json
      
      - name: Auto-fix JavaScript errors
        run: eslint . --ext .js,.html --fix || true
      
      - name: Check for HTML errors
        run: htmlhint "**/*.html" || true
      
      - name: Commit auto-fixes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-fix: Code quality improvements" && git push)
